[project]
name = "dimwit"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "jax",
    "einops",
    "numpy>=2.0",
    "matplotlib",
    "shapely>=2.1.2",
    "networkx>=3.6.1",
    "geopandas>=1.1.2",
]
